### ISSUE TITLE
乐观锁冲突重试时并没有更新版本号

### ISSUE THREAD

**Issue by roverbeta** [zaiyunduan123/jesper_seckill#10]
do {
            numAttempts++;
            try {
                ret = goodsMapper.reduceStockByVersion(sg);
            } catch (Exception e) {
                e.printStackTrace();
            }
            if (ret != 0)
                break;
        } while (numAttempts < DEFAULT_MAX_RETRIES);

**Comment by zaiyunduan123** [comment]
已修复，谢谢
