### ISSUE TITLE
如果version失效了，更新失败 再次执行时没有取出表中最新的version，所以不管循环几次，更新也是失败的？？？？

### ISSUE THREAD

**Issue by chen393804997** [zaiyunduan123/jesper_seckill#13]
/**
     * 减少库存，每次减一
     *
     * @return
     */
    public boolean reduceStock(GoodsVo goods) {
        int numAttempts = 0;
        int ret = 0;
        SeckillGoods sg = new SeckillGoods();
        sg.setGoodsId(goods.getId());
        sg.setVersion(goods.getVersion());
        do {
            numAttempts++;
            try {
                //TODO 如果version失效了，更新失败 再次执行时没有取出表中最新的version，所以不管循环几次，更新也是失败的？？？？
                ret = goodsMapper.reduceStockByVersion(sg);
            } catch (Exception e) {
                e.printStackTrace();
            }
            if (ret != 0)
                break;
        } while (numAttempts < DEFAULT_MAX_RETRIES);

        return ret > 0;
    }

**Comment by zaiyunduan123** [comment]
已修复，谢谢
