### ISSUE TITLE
redis password

### ISSUE THREAD

**Issue by jarqi** [zaiyunduan123/jesper_seckill#20]
redis pass 没有通过配置读取到实例化中，导致redis 设置了pass就会报错。
        JedisPool jp = new JedisPool(config, redisConfig.getHost(), redisConfig.getPort(),
                redisConfig.getTimeout()*1000, redisConfig.getPassword(), 0);
git中没有加redisConifg.getPassword()
在RedisPoolFactory.java中

**Comment by zaiyunduan123** [comment]
已修复，谢谢
