### ISSUE TITLE
启动步骤

### ISSUE THREAD

**Issue by szkb** [zaiyunduan123/jesper_seckill#27]
方便详细写下启动步骤吗，我这种小白来学习的话就是一路坑。

**Comment by zaiyunduan123** [comment]
1、把sql脚本在你MySQL跑一遍，生成数据库表和数据。
2、启动项目需要用到的组件Redis和RabbitMQ
3、最后直接运行启动类MainApplication.java就可以了

**Comment by josnname** [comment]
项目启动后。访问不了。是怎么回事一直404.idea也没有报错。想问下大佬是怎么回事。
