### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by liu165** [zaiyunduan123/jesper_seckill#31]
怎么运行

**Comment by Winter95** [comment]
同样请教 有没有具体保姆式教程 数据库表示连接不上 万分感谢

**Comment by zaiyunduan123** [comment]
1、把sql脚本在你MySQL跑一遍，生成数据库表和数据。
2、启动项目需要用到的组件Redis和RabbitMQ
3、最后直接运行启动类MainApplication.java就可以了
