### ISSUE TITLE
预减库存会不会存在卖不完的情况

### ISSUE THREAD

**Issue by bigeyefish** [zaiyunduan123/jesper_seckill#4]
SeckillController.list 方法中，先预减库存，然后判断是否重复秒杀。如果重复秒杀或者下订单异常，应该会出现有库存，但是返回秒杀完毕情况

**Comment by zaiyunduan123** [comment]
以前就知道到这个问题，但忘了改，现在改回来了，当预减库存小于0时，再将数据库商品信息加载到redis和本地内存，如果这次再小于0，这就返回秒杀完毕
