### ISSUE TITLE
乐观锁的version number在更新时没有传送

### ISSUE THREAD

**Issue by baijy** [zaiyunduan123/jesper_seckill#5]
两个问题
1、更新库存时没有送version number，所以更新库存失败
2、秒杀成功以后，返回的int 永远是1，作为订单号返回，是查不到订单的

GoodsVo
增加
int version 和getter setter

GoodsMapper
getGoodsVoByGoodsId 增加返回 sg.version

GoodsService
reduceStock()方法增加
sg.setVersion(goods.getVersion());

OrderService
createOrder()方法
订单号要从实体类中取，否则update返回的永远是1
long orderId = orderInfo.getId();

**Comment by baijy** [comment]
自己把这个项目理清调通以后，确实学到一些技术点，感谢

**Comment by zaiyunduan123** [comment]
确定存在问题，已修复，感谢
